version: "3.8"
services:
  frontend:
    container_name: frontend
    build:
      context: .
      # dockerfile: Dockerfile
      # target: dev
    restart: always
    command: pnpm start
    # environment:
    #   - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3003:3000